# Generated by Django 3.1.1 on 2020-09-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('kind', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('Writer', 'Writer')], default='actor', max_length=8)),
                ('photo', models.ImageField(null=True, upload_to='person_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
